server:
  port: 9000
  servlet:
    context-path: /test
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT&useSSL=false
  servlet:
    multipart:
      max-file-size: 2048MB

mybatis-plus:
  configuration.log-impl:
    org.apache.ibatis.logging.stdout.StdOutImpl

# clamav 文件杀毒服务器连接配置
clamav:
  # 服务器ip
  ipAddress: 192.168.31.115
  port: 13310
  timeout: 5000000